server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/loans/**